// Authentication
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATION_INIT = 'AUTHENTICATION_INIT'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const AUTHENTICATION_EXPIRED = 'AUTHENTICATION_EXPIRED'

// Registration
export const REGISTRATE = 'REGISTRATE'
export const REGISTRATION_INIT = 'REGISTRATION_INIT'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const VALIDATE_EMAIL = 'VALIDATE_EMAIL'
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS'
export const VALIDATE_EMAIL_FAILED = 'VALIDATE_EMAIL_FAILED'

// Restore Password
export const RESTORE_PASSWORD = 'RESTORE_PASSWORD'
export const RESTORE_PASSWORD_INIT = 'RESTORE_PASSWORD_INIT'
export const RESTORE_PASSWORD_SUCCESS = 'RESTORE_PASSWORD_SUCCESS'
export const RESTORE_PASSWORD_ERROR = 'RESTORE_PASSWORD_ERROR'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_INIT = 'CHANGE_PASSWORD_INIT'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const VALIDATE_CHANGE_PASSWORD_TOKEN = 'VALIDATE_CHANGE_PASSWORD_TOKEN'
export const VALIDATE_CHANGE_PASSWORD_TOKEN_SUCCESS = 'VALIDATE_CHANGE_PASSWORD_TOKEN_SUCCESS'
export const VALIDATE_CHANGE_PASSWORD_TOKEN_FAILED = 'VALIDATE_CHANGE_PASSWORD_TOKEN_FAILED'

// Roles
export const FETCH_ROLES = 'FETCH_ROLES'
export const SET_ROLES = 'SET_ROLES'
export const FETCH_ROLE = 'FETCH_ROLE'
export const SET_ROLE = 'SET_ROLE'

export const UPDATE_ROLE_NAME = 'UPDATE_ROLE_NAME'

export const SAVE_ROLE = 'SAVE_ROLE'
export const SAVE_ROLE_SUCCESS = 'SAVE_ROLE_SUCCESS'
export const SAVE_ROLE_ERROR = 'SAVE_ROLE_ERROR'
export const SAVE_ROLE_FINISH = 'SAVE_ROLE_FINISH'

export const DELETE_ROLE = 'DELETE_ROLE'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR'
export const DELETE_ROLE_FINISH = 'DELETE_ROLE_FINISH'

export const ROLES_ERROR = 'ROLES_ERROR'
export const ROLE_ERROR = 'ROLE_ERROR'

// Home
export const HOME_ERROR = 'HOME_ERROR'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// User
export const FETCH_LOGGED_IN_USER = 'FETCH_LOGGED_IN_USER'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const UPDATE_USER_LASTNAME = 'UPDATE_USER_LASTNAME'
export const UPDATE_USER_DNI = 'UPDATE_USER_DNI'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_DNI_DOCUMENT = 'UPDATE_DNI_DOCUMENT'
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'
export const UPDATE_USER_PHONENUMBER = 'UPDATE_USER_PHONENUMBER'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR'
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_FINISH = 'SAVE_USER_FINISH'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FINISH = 'LOGOUT_USER_FINISH'
export const SAVE_USER_PASSWORD = 'SAVE_USER_PASSWORD'
export const SAVE_USER_PASSWORD_SUCCESS = 'SAVE_USER_PASSWORD_SUCCESS'
export const SAVE_USER_PASSWORD_ERROR = 'SAVE_USER_PASSWORD_ERROR'
export const USER_ERROR = 'USER_ERROR'
export const FETCH_USERS = 'FETCH_USERS'
export const SET_USERS = 'SET_USERS'
export const USERS_ERROR = 'USERS_ERROR'
export const FETCH_USER = 'FETCH_USER'
export const SET_USER = 'SET_USER'
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const CHANGE_USER_STATUS_ERROR = 'CHANGE_USER_STATUS_ERROR'
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS'
export const SAVE_USER_ANON = 'SAVE_USER_ANON'
export const UPDATE_USER_USERNAME = 'UPDATE_USER_USERNAME'
export const CHANGE_USER_STATUS_FINISH = 'CHANGE_USER_STATUS_FINISH'
