// Authentication
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATION_INIT = 'AUTHENTICATION_INIT'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const AUTHENTICATION_EXPIRED = 'AUTHENTICATION_EXPIRED'

// Registration
export const REGISTRATE = 'REGISTRATE'
export const REGISTRATION_INIT = 'REGISTRATION_INIT'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const VALIDATE_EMAIL = 'VALIDATE_EMAIL'
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS'
export const VALIDATE_EMAIL_FAILED = 'VALIDATE_EMAIL_FAILED'

// Restore Password
export const RESTORE_PASSWORD = 'RESTORE_PASSWORD'
export const RESTORE_PASSWORD_INIT = 'RESTORE_PASSWORD_INIT'
export const RESTORE_PASSWORD_SUCCESS = 'RESTORE_PASSWORD_SUCCESS'
export const RESTORE_PASSWORD_ERROR = 'RESTORE_PASSWORD_ERROR'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_INIT = 'CHANGE_PASSWORD_INIT'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const VALIDATE_CHANGE_PASSWORD_TOKEN = 'VALIDATE_CHANGE_PASSWORD_TOKEN'
export const VALIDATE_CHANGE_PASSWORD_TOKEN_SUCCESS = 'VALIDATE_CHANGE_PASSWORD_TOKEN_SUCCESS'
export const VALIDATE_CHANGE_PASSWORD_TOKEN_FAILED = 'VALIDATE_CHANGE_PASSWORD_TOKEN_FAILED'

// Roles
export const FETCH_ROLES = 'FETCH_ROLES'
export const SET_ROLES = 'SET_ROLES'
export const FETCH_ROLE = 'FETCH_ROLE'
export const SET_ROLE = 'SET_ROLE'

export const UPDATE_ROLE_NAME = 'UPDATE_ROLE_NAME'

export const SAVE_ROLE = 'SAVE_ROLE'
export const SAVE_ROLE_SUCCESS = 'SAVE_ROLE_SUCCESS'
export const SAVE_ROLE_ERROR = 'SAVE_ROLE_ERROR'
export const SAVE_ROLE_FINISH = 'SAVE_ROLE_FINISH'

export const DELETE_ROLE = 'DELETE_ROLE'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR'
export const DELETE_ROLE_FINISH = 'DELETE_ROLE_FINISH'

export const ROLES_ERROR = 'ROLES_ERROR'
export const ROLE_ERROR = 'ROLE_ERROR'

// Home
export const HOME_ERROR = 'HOME_ERROR'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// User
export const FETCH_LOGGED_IN_USER = 'FETCH_LOGGED_IN_USER'
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const UPDATE_USER_LASTNAME = 'UPDATE_USER_LASTNAME'
export const UPDATE_USER_DNI = 'UPDATE_USER_DNI'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_DNI_DOCUMENT = 'UPDATE_DNI_DOCUMENT'
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'
export const UPDATE_USER_PHONENUMBER = 'UPDATE_USER_PHONENUMBER'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR'
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_FINISH = 'SAVE_USER_FINISH'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FINISH = 'LOGOUT_USER_FINISH'
export const SAVE_USER_PASSWORD = 'SAVE_USER_PASSWORD'
export const SAVE_USER_PASSWORD_SUCCESS = 'SAVE_USER_PASSWORD_SUCCESS'
export const SAVE_USER_PASSWORD_ERROR = 'SAVE_USER_PASSWORD_ERROR'
export const USER_ERROR = 'USER_ERROR'
export const FETCH_USERS = 'FETCH_USERS'
export const SET_USERS = 'SET_USERS'
export const USERS_ERROR = 'USERS_ERROR'
export const FETCH_USER = 'FETCH_USER'
export const SET_USER = 'SET_USER'
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const CHANGE_USER_STATUS_ERROR = 'CHANGE_USER_STATUS_ERROR'
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS'
export const SAVE_USER_ANON = 'SAVE_USER_ANON'
export const UPDATE_USER_USERNAME = 'UPDATE_USER_USERNAME'
export const CHANGE_USER_STATUS_FINISH = 'CHANGE_USER_STATUS_FINISH'

// Course
export const FETCH_COURSE = 'FETCH_COURSE'
export const SET_COURSE = 'SET_COURSE'
export const COURSES_ERROR = 'COURSES_ERROR'
export const FETCH_COURSES = 'FETCH_COURSES'
export const SET_COURSES = 'SET_COURSES'
export const SAVE_COURSE = 'SAVE_COURSE'
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS'
export const SAVE_COURSE_ERROR = 'SAVE_COURSE_ERROR'
export const SAVE_COURSE_FINISH = 'SAVE_COURSE_FINISH'

// Outcome Categorys
export const FETCH_OUTCOMECATEGORY = 'FETCH_OUTCOMECATEGORY'
export const SET_OUTCOMECATEGORY = 'SET_OUTCOMECATEGORY'
export const OUTCOMECATEGORYS_ERROR = 'OUTCOMECATEGORYS_ERROR'
export const FETCH_OUTCOMECATEGORYS = 'FETCH_OUTCOMECATEGORYS'
export const SET_OUTCOMECATEGORYS = 'SET_OUTCOMECATEGORYS'
export const SAVE_OUTCOMECATEGORY = 'SAVE_OUTCOMECATEGORY'
export const SAVE_OUTCOMECATEGORY_SUCCESS = 'SAVE_OUTCOMECATEGORY_SUCCESS'
export const SAVE_OUTCOMECATEGORY_ERROR = 'SAVE_OUTCOMECATEGORY_ERROR'
export const SAVE_OUTCOMECATEGORY_FINISH = 'SAVE_OUTCOMECATEGORY_FINISH'

// Course Enrollments
export const FETCH_COURSE_ENROLLMENT = 'FETCH_COURSE_ENROLLMENT'
export const SET_COURSE_ENROLLMENT = 'SET_COURSE_ENROLLMENT'
export const COURSE_ENROLLMENTS_ERROR = 'COURSE_ENROLLMENTS_ERROR'
export const FETCH_COURSE_ENROLLMENTS = 'FETCH_COURSE_ENROLLMENTS'
export const SET_COURSE_ENROLLMENTS = 'SET_COURSE_ENROLLMENTS'
export const SAVE_COURSE_ENROLLMENT = 'SAVE_COURSE_ENROLLMENT'
export const SAVE_COURSE_ENROLLMENT_SUCCESS = 'SAVE_COURSE_ENROLLMENT_SUCCESS'
export const SAVE_COURSE_ENROLLMENT_ERROR = 'SAVE_COURSE_ENROLLMENT_ERROR'
export const SAVE_COURSE_ENROLLMENT_FINISH = 'SAVE_COURSE_ENROLLMENT_FINISH'

// Incomes
export const FETCH_INCOME = 'FETCH_INCOME'
export const SET_INCOME = 'SET_INCOME'
export const INCOMES_ERROR = 'INCOMES_ERROR'
export const FETCH_INCOMES = 'FETCH_INCOMES'
export const SET_INCOMES = 'SET_INCOMES'
export const SAVE_INCOME = 'SAVE_INCOME'
export const SAVE_INCOME_SUCCESS = 'SAVE_INCOME_SUCCESS'
export const SAVE_INCOME_ERROR = 'SAVE_INCOME_ERROR'
export const SAVE_INCOME_FINISH = 'SAVE_INCOME_FINISH'

// Outcomes
export const FETCH_OUTCOME = 'FETCH_OUTCOME'
export const SET_OUTCOME = 'SET_OUTCOME'
export const OUTCOMES_ERROR = 'OUTCOMES_ERROR'
export const FETCH_OUTCOMES = 'FETCH_OUTCOMES'
export const SET_OUTCOMES = 'SET_OUTCOMES'
export const SAVE_OUTCOME = 'SAVE_OUTCOME'
export const SAVE_OUTCOME_SUCCESS = 'SAVE_OUTCOME_SUCCESS'
export const SAVE_OUTCOME_ERROR = 'SAVE_OUTCOME_ERROR'
export const SAVE_OUTCOME_FINISH = 'SAVE_OUTCOME_FINISH'

// Dashboards
export const FETCH_USER_STATS = 'FETCH_USER_STATS'
export const SET_USER_STATS = 'SET_USER_STATS'
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR'

// Timelines
export const FETCH_TIMELINE = 'FETCH_TIMELINE'
export const SET_TIMELINE = 'SET_TIMELINE'
export const TIMELINES_ERROR = 'TIMELINES_ERROR'
export const FETCH_TIMELINES = 'FETCH_TIMELINES'
export const SET_TIMELINES = 'SET_TIMELINES'
export const SAVE_TIMELINE = 'SAVE_TIMELINE'
export const SAVE_TIMELINE_SUCCESS = 'SAVE_TIMELINE_SUCCESS'
export const SAVE_TIMELINE_ERROR = 'SAVE_TIMELINE_ERROR'
export const SAVE_TIMELINE_FINISH = 'SAVE_TIMELINE_FINISH'
